[2025-10-19T15:44:16.730+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-19T15:44:16.781+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wiki_trending_pipeline.categorize_pages manual__2025-10-19T15:38:17.345526+00:00 [queued]>
[2025-10-19T15:44:16.790+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wiki_trending_pipeline.categorize_pages manual__2025-10-19T15:38:17.345526+00:00 [queued]>
[2025-10-19T15:44:16.790+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 3
[2025-10-19T15:44:16.803+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): categorize_pages> on 2025-10-19 15:38:17.345526+00:00
[2025-10-19T15:44:16.814+0000] {standard_task_runner.py:63} INFO - Started process 2373 to run task
[2025-10-19T15:44:16.820+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'wiki_trending_pipeline', 'categorize_pages', 'manual__2025-10-19T15:38:17.345526+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/wiki_top_pages_dag.py', '--cfg-path', '/tmp/tmpoqx9pi_e']
[2025-10-19T15:44:16.824+0000] {standard_task_runner.py:91} INFO - Job 76: Subtask categorize_pages
[2025-10-19T15:44:16.921+0000] {task_command.py:426} INFO - Running <TaskInstance: wiki_trending_pipeline.categorize_pages manual__2025-10-19T15:38:17.345526+00:00 [running]> on host 6045c73eb554
[2025-10-19T15:44:17.103+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-engineering' AIRFLOW_CTX_DAG_ID='wiki_trending_pipeline' AIRFLOW_CTX_TASK_ID='categorize_pages' AIRFLOW_CTX_EXECUTION_DATE='2025-10-19T15:38:17.345526+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-19T15:38:17.345526+00:00'
[2025-10-19T15:44:17.103+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-19T15:44:17.248+0000] {logging_mixin.py:188} INFO - ‚ùå Ollama not accessible: HTTPConnectionPool(host='host.docker.internal', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x763823fe2f10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-10-19T15:44:17.249+0000] {logging_mixin.py:188} INFO -    Make sure to run: ollama serve
[2025-10-19T15:44:17.250+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-19T15:44:17.251+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/utils/categorize_pages.py", line 30, in categorize_pages
    raise Exception("Ollama not running. Start with: ollama serve")
Exception: Ollama not running. Start with: ollama serve
[2025-10-19T15:44:17.288+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=wiki_trending_pipeline, task_id=categorize_pages, execution_date=20251019T153817, start_date=20251019T154416, end_date=20251019T154417
[2025-10-19T15:44:17.308+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 76 for task categorize_pages (Ollama not running. Start with: ollama serve; 2373)
[2025-10-19T15:44:17.350+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-19T15:44:17.425+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-19T15:44:17.428+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
