[2025-10-18T10:18:44.895+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-18T10:18:44.946+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wiki_trending_pipeline.clean_top_pages manual__2025-10-18T10:12:19.965456+00:00 [queued]>
[2025-10-18T10:18:44.958+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wiki_trending_pipeline.clean_top_pages manual__2025-10-18T10:12:19.965456+00:00 [queued]>
[2025-10-18T10:18:44.959+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2025-10-18T10:18:44.974+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): clean_top_pages> on 2025-10-18 10:12:19.965456+00:00
[2025-10-18T10:18:44.986+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=437) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-18T10:18:44.987+0000] {standard_task_runner.py:63} INFO - Started process 438 to run task
[2025-10-18T10:18:44.988+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'wiki_trending_pipeline', 'clean_top_pages', 'manual__2025-10-18T10:12:19.965456+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/wiki_dag/wiki_top_pages_dag.py', '--cfg-path', '/tmp/tmphh87z0ge']
[2025-10-18T10:18:44.992+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask clean_top_pages
[2025-10-18T10:18:45.022+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-18T10:18:45.073+0000] {task_command.py:426} INFO - Running <TaskInstance: wiki_trending_pipeline.clean_top_pages manual__2025-10-18T10:12:19.965456+00:00 [running]> on host 7f732f787a74
[2025-10-18T10:18:45.180+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='wiki_trending_pipeline' AIRFLOW_CTX_TASK_ID='clean_top_pages' AIRFLOW_CTX_EXECUTION_DATE='2025-10-18T10:12:19.965456+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-18T10:12:19.965456+00:00'
[2025-10-18T10:18:45.181+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-18T10:18:45.684+0000] {local_task_job_runner.py:124} ERROR - Received SIGTERM. Terminating subprocesses
[2025-10-18T10:18:45.692+0000] {process_utils.py:132} INFO - Sending 15 to group 438. PIDs of all processes in the group: [439, 438]
[2025-10-18T10:18:45.693+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 438
[2025-10-18T10:18:45.695+0000] {taskinstance.py:2607} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-10-18T10:18:45.697+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-18T10:18:45.715+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tasks/clean_top_pages.py", line 31, in clean_top_pages
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 104, in launch_gateway
    time.sleep(0.1)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2609, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-10-18T10:18:45.727+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=wiki_trending_pipeline, task_id=clean_top_pages, execution_date=20251018T101219, start_date=20251018T101844, end_date=20251018T101845
[2025-10-18T10:18:45.830+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=438, status='terminated', exitcode=2, started='10:18:44') (438) terminated with exit code 2
[2025-10-18T10:18:45.833+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=439, status='terminated', started='10:18:44') (439) terminated with exit code None
[2025-10-18T10:18:45.834+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 143
[2025-10-18T10:18:45.876+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
